// <auto-generated />
using System;
using HumanitarianProjectManagement.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumanitarianProjectManagement.Migrations
{
    [DbContext(typeof(HpmDbContext))]
    [Migration("20250615225544_CascadeFix_AllRelationships")]
    partial class CascadeFix_AllRelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HumanitarianProjectManagement.BudgetSubCategory", b =>
                {
                    b.Property<Guid>("BudgetSubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MainCategory")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryCodeSuffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BudgetSubCategoryID");

                    b.HasIndex("ProjectId");

                    b.ToTable("BudgetSubCategory");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BudgetID")
                        .HasColumnType("int");

                    b.Property<int>("OutputID")
                        .HasColumnType("int");

                    b.Property<string>("PlannedMonths")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityID");

                    b.HasIndex("BudgetID");

                    b.HasIndex("OutputID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BeneficiaryListID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("HouseholdSize")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VulnerabilityCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryID");

                    b.HasIndex("BeneficiaryListID");

                    b.ToTable("Beneficiary");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.BeneficiaryList", b =>
                {
                    b.Property<int>("BeneficiaryListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("BeneficiaryListID");

                    b.HasIndex("ProjectID");

                    b.ToTable("BeneficiaryList");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("BudgetID");

                    b.HasIndex("ApprovedByUserID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.DetailedBudgetLine", b =>
                {
                    b.Property<Guid>("DetailedBudgetLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudgetSubCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("PercentageChargedToCBPF")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DetailedBudgetLineID");

                    b.HasIndex("BudgetSubCategoryID");

                    b.HasIndex("ProjectId");

                    b.ToTable("DetailedBudgetLine");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BeneficiaryID")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackSource")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FeedbackType")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("RecordedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("FeedbackID");

                    b.HasIndex("BeneficiaryID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("RecordedByUserID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.FollowUpVisit", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BeneficiaryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitedByUserID")
                        .HasColumnType("int");

                    b.HasKey("VisitID");

                    b.HasIndex("BeneficiaryID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("VisitedByUserID");

                    b.ToTable("FollowUpVisit");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ItemizedBudgetDetail", b =>
                {
                    b.Property<Guid>("ItemizedBudgetDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentBudgetLineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemizedBudgetDetailID");

                    b.HasIndex("ParentBudgetLineID");

                    b.ToTable("ItemizedBudgetDetail");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Outcome", b =>
                {
                    b.Property<int>("OutcomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OutcomeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("OutcomeID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Outcome");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Output", b =>
                {
                    b.Property<int>("OutputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OutcomeID")
                        .HasColumnType("int");

                    b.Property<string>("OutputDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutputID");

                    b.HasIndex("OutcomeID");

                    b.ToTable("Output");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Donor")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerUserID")
                        .HasColumnType("int");

                    b.Property<string>("OverallObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("SectionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal?>("TotalBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectID");

                    b.HasIndex("ManagerUserID");

                    b.HasIndex("SectionID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectIndicator", b =>
                {
                    b.Property<int>("ProjectIndicatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualValue")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BaselineValue")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndicatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKeyIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("MeansOfVerification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutputID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetBoys")
                        .HasColumnType("int");

                    b.Property<int>("TargetGirls")
                        .HasColumnType("int");

                    b.Property<int>("TargetMen")
                        .HasColumnType("int");

                    b.Property<int>("TargetTotal")
                        .HasColumnType("int");

                    b.Property<string>("TargetValue")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("TargetWomen")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ProjectIndicatorID");

                    b.HasIndex("OutputID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectIndicator");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Achievements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Challenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(260)")
                        .HasMaxLength(260);

                    b.Property<string>("FinancialSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonsLearned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ReportType")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ReportingPeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReportingPeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SubmittedByUserID");

                    b.ToTable("ProjectReport");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BudgetID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ItemSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("TotalCost")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(20, 2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseID");

                    b.HasIndex("BudgetID");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseID")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseOrderID");

                    b.HasIndex("ApprovedByUserID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("PurchaseID");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Salary", b =>
                {
                    b.Property<int>("SalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BudgetID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NumberOfMonths")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("TotalSalaryAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(20, 4)");

                    b.HasKey("SalaryID");

                    b.HasIndex("BudgetID");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Section", b =>
                {
                    b.Property<int>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("SectionID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.StockItem", b =>
                {
                    b.Property<int>("StockItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastStockUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxStockLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("StockItemID");

                    b.ToTable("StockItem");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.StockTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityID")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiaryID")
                        .HasColumnType("int");

                    b.Property<string>("DistributedTo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("StockItemID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TransactionID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("BeneficiaryID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("PurchaseOrderID");

                    b.HasIndex("RecordedByUserID");

                    b.HasIndex("StockItemID");

                    b.ToTable("StockTransaction");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.VerificationMean", b =>
                {
                    b.Property<int>("VerificationMeanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("IndicatorID")
                        .HasColumnType("int");

                    b.Property<string>("MeanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleParty")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("VerificationMeanID");

                    b.HasIndex("IndicatorID");

                    b.ToTable("VerificationMeans");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.BudgetSubCategory", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("BudgetSubCategories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Activity", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Budget", null)
                        .WithMany("Activities")
                        .HasForeignKey("BudgetID");

                    b.HasOne("HumanitarianProjectManagement.Models.Output", "Output")
                        .WithMany("Activities")
                        .HasForeignKey("OutputID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Beneficiary", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.BeneficiaryList", "BeneficiaryList")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("BeneficiaryListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.BeneficiaryList", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("BeneficiaryLists")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Budget", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.User", "ApprovedByUser")
                        .WithMany("ApprovedBudgets")
                        .HasForeignKey("ApprovedByUserID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("Budgets")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.DetailedBudgetLine", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.BudgetSubCategory", "BudgetSubCategory")
                        .WithMany("DetailedBudgetLines")
                        .HasForeignKey("BudgetSubCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("DetailedBudgetLines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Feedback", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Beneficiary", "Beneficiary")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BeneficiaryID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProjectID");

                    b.HasOne("HumanitarianProjectManagement.Models.User", "RecordedByUser")
                        .WithMany("RecordedFeedback")
                        .HasForeignKey("RecordedByUserID");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.FollowUpVisit", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Beneficiary", "Beneficiary")
                        .WithMany("FollowUpVisits")
                        .HasForeignKey("BeneficiaryID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("FollowUpVisits")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanitarianProjectManagement.Models.User", "VisitedByUser")
                        .WithMany("ConductedFollowUpVisits")
                        .HasForeignKey("VisitedByUserID");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ItemizedBudgetDetail", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.DetailedBudgetLine", "ParentBudgetLine")
                        .WithMany("ItemizedDetails")
                        .HasForeignKey("ParentBudgetLineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Outcome", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("Outcomes")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Output", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Outcome", "Outcome")
                        .WithMany("Outputs")
                        .HasForeignKey("OutcomeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Project", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.User", "ManagerUser")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerUserID");

                    b.HasOne("HumanitarianProjectManagement.Models.Section", "Section")
                        .WithMany("Projects")
                        .HasForeignKey("SectionID");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectIndicator", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Output", "Output")
                        .WithMany("ProjectIndicators")
                        .HasForeignKey("OutputID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("ProjectIndicators")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectReport", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("ProjectReports")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanitarianProjectManagement.Models.User", "SubmittedByUser")
                        .WithMany("SubmittedProjectReports")
                        .HasForeignKey("SubmittedByUserID");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Purchase", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Budget", "Budget")
                        .WithMany("Purchases")
                        .HasForeignKey("BudgetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.PurchaseOrder", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.User", "ApprovedByUser")
                        .WithMany("ApprovedPurchaseOrders")
                        .HasForeignKey("ApprovedByUserID");

                    b.HasOne("HumanitarianProjectManagement.Models.User", "CreatedByUser")
                        .WithMany("CreatedPurchaseOrders")
                        .HasForeignKey("CreatedByUserID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanitarianProjectManagement.Models.Purchase", "BudgetItemPurchase")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("PurchaseID");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Salary", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Budget", "Budget")
                        .WithMany("Salaries")
                        .HasForeignKey("BudgetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.StockTransaction", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityID");

                    b.HasOne("HumanitarianProjectManagement.Models.Beneficiary", "Beneficiary")
                        .WithMany("StockTransactions")
                        .HasForeignKey("BeneficiaryID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProjectID");

                    b.HasOne("HumanitarianProjectManagement.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("StockTransactions")
                        .HasForeignKey("PurchaseOrderID");

                    b.HasOne("HumanitarianProjectManagement.Models.User", "RecordedByUser")
                        .WithMany("RecordedStockTransactions")
                        .HasForeignKey("RecordedByUserID");

                    b.HasOne("HumanitarianProjectManagement.Models.StockItem", "StockItem")
                        .WithMany("StockTransactions")
                        .HasForeignKey("StockItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.UserRole", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanitarianProjectManagement.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.VerificationMean", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.ProjectIndicator", "ProjectIndicator")
                        .WithMany("VerificationMeans")
                        .HasForeignKey("IndicatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
