// <auto-generated />
using System;
using HumanitarianProjectManagement.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumanitarianProjectManagement.Migrations
{
    [DbContext(typeof(HpmDbContext))]
    partial class HpmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutputID")
                        .HasColumnType("int");

                    b.Property<string>("PlannedMonths")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityID");

                    b.HasIndex("OutputID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BeneficiaryListID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HouseholdSize")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VulnerabilityCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryID");

                    b.HasIndex("BeneficiaryListID");

                    b.ToTable("Beneficiary");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.BeneficiaryList", b =>
                {
                    b.Property<int>("BeneficiaryListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("BeneficiaryListID");

                    b.HasIndex("ProjectID");

                    b.ToTable("BeneficiaryList");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.DetailedBudgetLine", b =>
                {
                    b.Property<int>("DetailedBudgetLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("ParentDetailedBudgetLineID")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentageChargedToCBPF")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DetailedBudgetLineID");

                    b.HasIndex("ParentDetailedBudgetLineID");

                    b.HasIndex("ProjectId");

                    b.ToTable("DetailedBudgetLine");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.FollowUpVisit", b =>
                {
                    b.Property<int>("FollowUpVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("FollowUpVisitID");

                    b.HasIndex("ProjectID");

                    b.ToTable("FollowUpVisit");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ItemizedBudgetDetail", b =>
                {
                    b.Property<int>("ItemizedBudgetDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentBudgetLineID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemizedBudgetDetailID");

                    b.HasIndex("ParentBudgetLineID");

                    b.ToTable("ItemizedBudgetDetail");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Outcome", b =>
                {
                    b.Property<int>("OutcomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OutcomeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("OutcomeID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Outcome");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Output", b =>
                {
                    b.Property<int>("OutputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OutcomeID")
                        .HasColumnType("int");

                    b.Property<string>("OutputDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutputID");

                    b.HasIndex("OutcomeID");

                    b.ToTable("Output");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Donor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerUserID")
                        .HasColumnType("int");

                    b.Property<string>("OverallObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectIndicator", b =>
                {
                    b.Property<int>("ProjectIndicatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActualValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaselineValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndicatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKeyIndicator")
                        .HasColumnType("bit");

                    b.Property<int?>("OutputID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectIndicatorID");

                    b.HasIndex("OutputID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectIndicator");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectReport", b =>
                {
                    b.Property<int>("ProjectReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("ProjectReportID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectReport");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "Full system access",
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Section", b =>
                {
                    b.Property<int>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bill@example.com",
                            FullName = "Bill Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$G.iV/z.B.A.n0l2wR0P0bOSr.1b.i.I.m.C.y.Y.s.W.t.b.b.U.m",
                            Username = "bill"
                        });
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Activity", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Output", "Output")
                        .WithMany("Activities")
                        .HasForeignKey("OutputID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Beneficiary", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.BeneficiaryList", "BeneficiaryList")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("BeneficiaryListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.BeneficiaryList", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("BeneficiaryLists")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.DetailedBudgetLine", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.DetailedBudgetLine", "ParentDetailedBudgetLine")
                        .WithMany("ChildDetailedBudgetLines")
                        .HasForeignKey("ParentDetailedBudgetLineID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("DetailedBudgetLines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Feedback", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.FollowUpVisit", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("FollowUpVisits")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ItemizedBudgetDetail", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.DetailedBudgetLine", "ParentBudgetLine")
                        .WithMany("ItemizedDetails")
                        .HasForeignKey("ParentBudgetLineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Outcome", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("Outcomes")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.Output", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Outcome", "Outcome")
                        .WithMany("Outputs")
                        .HasForeignKey("OutcomeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectIndicator", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Output", "Output")
                        .WithMany("ProjectIndicators")
                        .HasForeignKey("OutputID");

                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("ProjectIndicators")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.ProjectReport", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Project", "Project")
                        .WithMany("ProjectReports")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanitarianProjectManagement.Models.UserRole", b =>
                {
                    b.HasOne("HumanitarianProjectManagement.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanitarianProjectManagement.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
